//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map(Locale.init)
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.nib` struct is generated, and contains static references to 3 nibs.
  struct nib {
    /// Nib `BudgetTableViewCell`.
    static let budgetTableViewCell = _R.nib._BudgetTableViewCell()
    /// Nib `BudgetTableViewHeader`.
    static let budgetTableViewHeader = _R.nib._BudgetTableViewHeader()
    /// Nib `TransactionTableViewCell`.
    static let transactionTableViewCell = _R.nib._TransactionTableViewCell()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "BudgetTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.budgetTableViewCell) instead")
    static func budgetTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.budgetTableViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "BudgetTableViewHeader", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.budgetTableViewHeader) instead")
    static func budgetTableViewHeader(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.budgetTableViewHeader)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "TransactionTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.transactionTableViewCell) instead")
    static func transactionTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.transactionTableViewCell)
    }
    #endif

    static func budgetTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> BudgetTableViewCell? {
      return R.nib.budgetTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? BudgetTableViewCell
    }

    static func budgetTableViewHeader(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> BudgetTableViewHeader? {
      return R.nib.budgetTableViewHeader.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? BudgetTableViewHeader
    }

    static func transactionTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TransactionTableViewCell? {
      return R.nib.transactionTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TransactionTableViewCell
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib {
    struct _BudgetTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "BudgetTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> BudgetTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? BudgetTableViewCell
      }

      fileprivate init() {}
    }

    struct _BudgetTableViewHeader: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "BudgetTableViewHeader"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> BudgetTableViewHeader? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? BudgetTableViewHeader
      }

      fileprivate init() {}
    }

    struct _TransactionTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "TransactionTableViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TransactionTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TransactionTableViewCell
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try main.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = LoginViewController

      let addBudgetTableViewController = StoryboardViewControllerResource<AddBudgetTableViewController>(identifier: "AddBudgetTableViewController")
      let addExpensesTableViewController = StoryboardViewControllerResource<AddExpensesTableViewController>(identifier: "AddExpensesTableViewController")
      let addMoneyTableViewController = StoryboardViewControllerResource<AddMoneyTableViewController>(identifier: "AddMoneyTableViewController")
      let budgetListViewController = StoryboardViewControllerResource<BudgetListViewController>(identifier: "BudgetListViewController")
      let bundle = R.hostingBundle
      let configurationViewController = StoryboardViewControllerResource<ConfigurationViewController>(identifier: "ConfigurationViewController")
      let historyListViewController = StoryboardViewControllerResource<HistoryListViewController>(identifier: "HistoryListViewController")
      let loginViewController = StoryboardViewControllerResource<LoginViewController>(identifier: "LoginViewController")
      let name = "Main"
      let tabBarViewController = StoryboardViewControllerResource<TabBarViewController>(identifier: "TabBarViewController")
      let visualizeBudgetTableViewController = StoryboardViewControllerResource<VisualizeBudgetTableViewController>(identifier: "VisualizeBudgetTableViewController")

      func addBudgetTableViewController(_: Void = ()) -> AddBudgetTableViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: addBudgetTableViewController)
      }

      func addExpensesTableViewController(_: Void = ()) -> AddExpensesTableViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: addExpensesTableViewController)
      }

      func addMoneyTableViewController(_: Void = ()) -> AddMoneyTableViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: addMoneyTableViewController)
      }

      func budgetListViewController(_: Void = ()) -> BudgetListViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: budgetListViewController)
      }

      func configurationViewController(_: Void = ()) -> ConfigurationViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: configurationViewController)
      }

      func historyListViewController(_: Void = ()) -> HistoryListViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: historyListViewController)
      }

      func loginViewController(_: Void = ()) -> LoginViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: loginViewController)
      }

      func tabBarViewController(_: Void = ()) -> TabBarViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: tabBarViewController)
      }

      func visualizeBudgetTableViewController(_: Void = ()) -> VisualizeBudgetTableViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: visualizeBudgetTableViewController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "gear", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'gear' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "pencil", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'pencil' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "tray", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tray' is used in storyboard 'Main', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.main().addBudgetTableViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'addBudgetTableViewController' could not be loaded from storyboard 'Main' as 'AddBudgetTableViewController'.") }
        if _R.storyboard.main().addExpensesTableViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'addExpensesTableViewController' could not be loaded from storyboard 'Main' as 'AddExpensesTableViewController'.") }
        if _R.storyboard.main().addMoneyTableViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'addMoneyTableViewController' could not be loaded from storyboard 'Main' as 'AddMoneyTableViewController'.") }
        if _R.storyboard.main().budgetListViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'budgetListViewController' could not be loaded from storyboard 'Main' as 'BudgetListViewController'.") }
        if _R.storyboard.main().configurationViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'configurationViewController' could not be loaded from storyboard 'Main' as 'ConfigurationViewController'.") }
        if _R.storyboard.main().historyListViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'historyListViewController' could not be loaded from storyboard 'Main' as 'HistoryListViewController'.") }
        if _R.storyboard.main().loginViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'loginViewController' could not be loaded from storyboard 'Main' as 'LoginViewController'.") }
        if _R.storyboard.main().tabBarViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'tabBarViewController' could not be loaded from storyboard 'Main' as 'TabBarViewController'.") }
        if _R.storyboard.main().visualizeBudgetTableViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'visualizeBudgetTableViewController' could not be loaded from storyboard 'Main' as 'VisualizeBudgetTableViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
