//
//  CategoriesRouter.swift
//  CleanSwiftExample
//
//  Created by admin on 4/25/20.
//  Copyright (c) 2020 admin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CategoriesRoutingLogic {
    func goToNextScreen(index: Int)
}

protocol CategoriesDataPassing {
    var dataStore: CategoriesDataStore? { get }
}

class CategoriesRouter: NSObject, CategoriesRoutingLogic, CategoriesDataPassing {
    weak var viewController: CategoriesViewController?
    var dataStore: CategoriesDataStore?
    
    // MARK: Routing
    
    
    
    // MARK: Navigation
    
    func goToNextScreen(index: Int) {
        if let newsViewController = R.storyboard.main.newsViewController() {
            newsViewController.router?.dataStore?.categoryIdentifier = self.dataStore?.getCategory(index: index).identifier
            self.viewController?.navigationController?.pushViewController(newsViewController, animated: true)
        }
    }
    
    // MARK: Passing data
    
    
}
