//
//  CategoryWorker.swift
//  CleanSwiftExample
//
//  Created by admin on 4/25/20.
//  Copyright (c) 2020 admin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol CategoryStoreProtocol {
    func insert(category: NativeCategory, completionHandler:() -> Void)
    func fetchAll(completionHandler:(_ categories: [NativeCategory]) -> Void)
    func fetch(id: String, completionHandler:(_ category: NativeCategory?) -> Void)
}

class CategoryWorker {
    
    var store: CategoryStoreProtocol
    
    init(store: CategoryStoreProtocol) {
        self.store = store
    }
    
    func insert(category: NativeCategory, completionHandler:() -> Void) {
        self.store.insert(category: category, completionHandler: completionHandler)
    }
    
    func fetchAll(completionHandler:(_ categories: [NativeCategory]) -> Void) {
        self.store.fetchAll(completionHandler: completionHandler)
    }
    
    func fetch(id: String, completionHandler:(_ category: NativeCategory?) -> Void) {
        self.store.fetch(id: id, completionHandler: completionHandler)
    }
}
