//
//  NewsInteractor.swift
//  CleanSwiftExample
//
//  Created by admin on 5/2/20.
//  Copyright (c) 2020 admin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsBusinessLogic {
    func requestDataSource(request: News.DataSource.Request)
}

protocol NewsDataStore {
    var categoryIdentifier: String? { get set }
}

class NewsInteractor: NewsBusinessLogic, NewsDataStore {
    
    var presenter: NewsPresentationLogic?
    var worker: NewsWorker?
    
    var storeWorker = CategoryWorker(store: CategoryRealmStore())
    
    var categoryIdentifier: String?
    
    func requestDataSource(request: News.DataSource.Request) {
        if let categoryIdentifier = self.categoryIdentifier {
            self.storeWorker.fetch(id: categoryIdentifier) { (category) in
                if let category = category {
                    self.presenter?.presentDataSource(response: News.DataSource.Response(news: category.news))
                }
            }
        }
    }
}
