//
//  NewsRouter.swift
//  CleanSwiftExample
//
//  Created by admin on 5/2/20.
//  Copyright (c) 2020 admin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NewsRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol NewsDataPassing {
    var dataStore: NewsDataStore? { get set }
}

class NewsRouter: NSObject, NewsRoutingLogic, NewsDataPassing {
    weak var viewController: NewsViewController?
    var dataStore: NewsDataStore?
    
    // MARK: Routing
    
    
    // MARK: Navigation
    
    
    // MARK: Passing data
    
}
