# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tarea5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'AFNetworking', '~> 4.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'NVActivityIndicatorView'
  pod 'Alamofire', '~> 5.1'
  pod 'R.swift'

  # Pods for Tarea5

end
